/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as OnboardingRouteRouteImport } from "./routes/onboarding/route"
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding/index"
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index"
import { Route as DashboardShellRouteRouteImport } from "./routes/dashboard/_shell/route"
import { Route as OnboardingCreateSignatureIndexRouteImport } from "./routes/onboarding/create-signature/index"
import { Route as InviteInviteIdIndexRouteImport } from "./routes/invite/$inviteId/index"
import { Route as DashboardSignatureCreateIndexRouteImport } from "./routes/dashboard/signature/create/index"
import { Route as DashboardEnvelopeCreateIndexRouteImport } from "./routes/dashboard/envelope/create/index"
import { Route as DashboardDocumentSignIndexRouteImport } from "./routes/dashboard/document/sign/index"
import { Route as DashboardShellConnectionsIndexRouteImport } from "./routes/dashboard/_shell/connections/index"
import { Route as DashboardEnvelopeCreateAddSignIndexRouteImport } from "./routes/dashboard/envelope/create/add-sign/index"
import { Route as DashboardShellSettingsTeamIndexRouteImport } from "./routes/dashboard/_shell/settings/team/index"
import { Route as DashboardShellSettingsProfileIndexRouteImport } from "./routes/dashboard/_shell/settings/profile/index"
import { Route as DashboardShellDocumentAllIndexRouteImport } from "./routes/dashboard/_shell/document/all/index"

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardShellRouteRoute = DashboardShellRouteRouteImport.update({
  id: "/_shell",
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingCreateSignatureIndexRoute =
  OnboardingCreateSignatureIndexRouteImport.update({
    id: "/create-signature/",
    path: "/create-signature/",
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const InviteInviteIdIndexRoute = InviteInviteIdIndexRouteImport.update({
  id: "/invite/$inviteId/",
  path: "/invite/$inviteId/",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSignatureCreateIndexRoute =
  DashboardSignatureCreateIndexRouteImport.update({
    id: "/signature/create/",
    path: "/signature/create/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEnvelopeCreateIndexRoute =
  DashboardEnvelopeCreateIndexRouteImport.update({
    id: "/envelope/create/",
    path: "/envelope/create/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDocumentSignIndexRoute =
  DashboardDocumentSignIndexRouteImport.update({
    id: "/document/sign/",
    path: "/document/sign/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardShellConnectionsIndexRoute =
  DashboardShellConnectionsIndexRouteImport.update({
    id: "/connections/",
    path: "/connections/",
    getParentRoute: () => DashboardShellRouteRoute,
  } as any)
const DashboardEnvelopeCreateAddSignIndexRoute =
  DashboardEnvelopeCreateAddSignIndexRouteImport.update({
    id: "/envelope/create/add-sign/",
    path: "/envelope/create/add-sign/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardShellSettingsTeamIndexRoute =
  DashboardShellSettingsTeamIndexRouteImport.update({
    id: "/settings/team/",
    path: "/settings/team/",
    getParentRoute: () => DashboardShellRouteRoute,
  } as any)
const DashboardShellSettingsProfileIndexRoute =
  DashboardShellSettingsProfileIndexRouteImport.update({
    id: "/settings/profile/",
    path: "/settings/profile/",
    getParentRoute: () => DashboardShellRouteRoute,
  } as any)
const DashboardShellDocumentAllIndexRoute =
  DashboardShellDocumentAllIndexRouteImport.update({
    id: "/document/all/",
    path: "/document/all/",
    getParentRoute: () => DashboardShellRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardShellRouteRouteWithChildren
  "/onboarding": typeof OnboardingRouteRouteWithChildren
  "/dashboard/": typeof DashboardIndexRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/invite/$inviteId/": typeof InviteInviteIdIndexRoute
  "/onboarding/create-signature/": typeof OnboardingCreateSignatureIndexRoute
  "/dashboard/connections/": typeof DashboardShellConnectionsIndexRoute
  "/dashboard/document/sign/": typeof DashboardDocumentSignIndexRoute
  "/dashboard/envelope/create/": typeof DashboardEnvelopeCreateIndexRoute
  "/dashboard/signature/create/": typeof DashboardSignatureCreateIndexRoute
  "/dashboard/document/all/": typeof DashboardShellDocumentAllIndexRoute
  "/dashboard/settings/profile/": typeof DashboardShellSettingsProfileIndexRoute
  "/dashboard/settings/team/": typeof DashboardShellSettingsTeamIndexRoute
  "/dashboard/envelope/create/add-sign/": typeof DashboardEnvelopeCreateAddSignIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardIndexRoute
  "/onboarding": typeof OnboardingIndexRoute
  "/invite/$inviteId": typeof InviteInviteIdIndexRoute
  "/onboarding/create-signature": typeof OnboardingCreateSignatureIndexRoute
  "/dashboard/connections": typeof DashboardShellConnectionsIndexRoute
  "/dashboard/document/sign": typeof DashboardDocumentSignIndexRoute
  "/dashboard/envelope/create": typeof DashboardEnvelopeCreateIndexRoute
  "/dashboard/signature/create": typeof DashboardSignatureCreateIndexRoute
  "/dashboard/document/all": typeof DashboardShellDocumentAllIndexRoute
  "/dashboard/settings/profile": typeof DashboardShellSettingsProfileIndexRoute
  "/dashboard/settings/team": typeof DashboardShellSettingsTeamIndexRoute
  "/dashboard/envelope/create/add-sign": typeof DashboardEnvelopeCreateAddSignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRouteRouteWithChildren
  "/onboarding": typeof OnboardingRouteRouteWithChildren
  "/dashboard/_shell": typeof DashboardShellRouteRouteWithChildren
  "/dashboard/": typeof DashboardIndexRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/invite/$inviteId/": typeof InviteInviteIdIndexRoute
  "/onboarding/create-signature/": typeof OnboardingCreateSignatureIndexRoute
  "/dashboard/_shell/connections/": typeof DashboardShellConnectionsIndexRoute
  "/dashboard/document/sign/": typeof DashboardDocumentSignIndexRoute
  "/dashboard/envelope/create/": typeof DashboardEnvelopeCreateIndexRoute
  "/dashboard/signature/create/": typeof DashboardSignatureCreateIndexRoute
  "/dashboard/_shell/document/all/": typeof DashboardShellDocumentAllIndexRoute
  "/dashboard/_shell/settings/profile/": typeof DashboardShellSettingsProfileIndexRoute
  "/dashboard/_shell/settings/team/": typeof DashboardShellSettingsTeamIndexRoute
  "/dashboard/envelope/create/add-sign/": typeof DashboardEnvelopeCreateAddSignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/"
    | "/onboarding/"
    | "/invite/$inviteId/"
    | "/onboarding/create-signature/"
    | "/dashboard/connections/"
    | "/dashboard/document/sign/"
    | "/dashboard/envelope/create/"
    | "/dashboard/signature/create/"
    | "/dashboard/document/all/"
    | "/dashboard/settings/profile/"
    | "/dashboard/settings/team/"
    | "/dashboard/envelope/create/add-sign/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboard"
    | "/onboarding"
    | "/invite/$inviteId"
    | "/onboarding/create-signature"
    | "/dashboard/connections"
    | "/dashboard/document/sign"
    | "/dashboard/envelope/create"
    | "/dashboard/signature/create"
    | "/dashboard/document/all"
    | "/dashboard/settings/profile"
    | "/dashboard/settings/team"
    | "/dashboard/envelope/create/add-sign"
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/_shell"
    | "/dashboard/"
    | "/onboarding/"
    | "/invite/$inviteId/"
    | "/onboarding/create-signature/"
    | "/dashboard/_shell/connections/"
    | "/dashboard/document/sign/"
    | "/dashboard/envelope/create/"
    | "/dashboard/signature/create/"
    | "/dashboard/_shell/document/all/"
    | "/dashboard/_shell/settings/profile/"
    | "/dashboard/_shell/settings/team/"
    | "/dashboard/envelope/create/add-sign/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  InviteInviteIdIndexRoute: typeof InviteInviteIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/": {
      id: "/onboarding/"
      path: "/"
      fullPath: "/onboarding/"
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/"
      fullPath: "/dashboard/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/_shell": {
      id: "/dashboard/_shell"
      path: ""
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardShellRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/onboarding/create-signature/": {
      id: "/onboarding/create-signature/"
      path: "/create-signature"
      fullPath: "/onboarding/create-signature/"
      preLoaderRoute: typeof OnboardingCreateSignatureIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    "/invite/$inviteId/": {
      id: "/invite/$inviteId/"
      path: "/invite/$inviteId"
      fullPath: "/invite/$inviteId/"
      preLoaderRoute: typeof InviteInviteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard/signature/create/": {
      id: "/dashboard/signature/create/"
      path: "/signature/create"
      fullPath: "/dashboard/signature/create/"
      preLoaderRoute: typeof DashboardSignatureCreateIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/envelope/create/": {
      id: "/dashboard/envelope/create/"
      path: "/envelope/create"
      fullPath: "/dashboard/envelope/create/"
      preLoaderRoute: typeof DashboardEnvelopeCreateIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/document/sign/": {
      id: "/dashboard/document/sign/"
      path: "/document/sign"
      fullPath: "/dashboard/document/sign/"
      preLoaderRoute: typeof DashboardDocumentSignIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/_shell/connections/": {
      id: "/dashboard/_shell/connections/"
      path: "/connections"
      fullPath: "/dashboard/connections/"
      preLoaderRoute: typeof DashboardShellConnectionsIndexRouteImport
      parentRoute: typeof DashboardShellRouteRoute
    }
    "/dashboard/envelope/create/add-sign/": {
      id: "/dashboard/envelope/create/add-sign/"
      path: "/envelope/create/add-sign"
      fullPath: "/dashboard/envelope/create/add-sign/"
      preLoaderRoute: typeof DashboardEnvelopeCreateAddSignIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/_shell/settings/team/": {
      id: "/dashboard/_shell/settings/team/"
      path: "/settings/team"
      fullPath: "/dashboard/settings/team/"
      preLoaderRoute: typeof DashboardShellSettingsTeamIndexRouteImport
      parentRoute: typeof DashboardShellRouteRoute
    }
    "/dashboard/_shell/settings/profile/": {
      id: "/dashboard/_shell/settings/profile/"
      path: "/settings/profile"
      fullPath: "/dashboard/settings/profile/"
      preLoaderRoute: typeof DashboardShellSettingsProfileIndexRouteImport
      parentRoute: typeof DashboardShellRouteRoute
    }
    "/dashboard/_shell/document/all/": {
      id: "/dashboard/_shell/document/all/"
      path: "/document/all"
      fullPath: "/dashboard/document/all/"
      preLoaderRoute: typeof DashboardShellDocumentAllIndexRouteImport
      parentRoute: typeof DashboardShellRouteRoute
    }
  }
}

interface DashboardShellRouteRouteChildren {
  DashboardShellConnectionsIndexRoute: typeof DashboardShellConnectionsIndexRoute
  DashboardShellDocumentAllIndexRoute: typeof DashboardShellDocumentAllIndexRoute
  DashboardShellSettingsProfileIndexRoute: typeof DashboardShellSettingsProfileIndexRoute
  DashboardShellSettingsTeamIndexRoute: typeof DashboardShellSettingsTeamIndexRoute
}

const DashboardShellRouteRouteChildren: DashboardShellRouteRouteChildren = {
  DashboardShellConnectionsIndexRoute: DashboardShellConnectionsIndexRoute,
  DashboardShellDocumentAllIndexRoute: DashboardShellDocumentAllIndexRoute,
  DashboardShellSettingsProfileIndexRoute:
    DashboardShellSettingsProfileIndexRoute,
  DashboardShellSettingsTeamIndexRoute: DashboardShellSettingsTeamIndexRoute,
}

const DashboardShellRouteRouteWithChildren =
  DashboardShellRouteRoute._addFileChildren(DashboardShellRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardShellRouteRoute: typeof DashboardShellRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDocumentSignIndexRoute: typeof DashboardDocumentSignIndexRoute
  DashboardEnvelopeCreateIndexRoute: typeof DashboardEnvelopeCreateIndexRoute
  DashboardSignatureCreateIndexRoute: typeof DashboardSignatureCreateIndexRoute
  DashboardEnvelopeCreateAddSignIndexRoute: typeof DashboardEnvelopeCreateAddSignIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardShellRouteRoute: DashboardShellRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDocumentSignIndexRoute: DashboardDocumentSignIndexRoute,
  DashboardEnvelopeCreateIndexRoute: DashboardEnvelopeCreateIndexRoute,
  DashboardSignatureCreateIndexRoute: DashboardSignatureCreateIndexRoute,
  DashboardEnvelopeCreateAddSignIndexRoute:
    DashboardEnvelopeCreateAddSignIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  OnboardingCreateSignatureIndexRoute: typeof OnboardingCreateSignatureIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
  OnboardingCreateSignatureIndexRoute: OnboardingCreateSignatureIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  InviteInviteIdIndexRoute: InviteInviteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
