import path from "node:path";
import type { ChainKey } from "../definitions/chain-key.js";
import { CHAIN_KEYS } from "../definitions/chain-key.js";
import type {
	ContractName,
	DeploymentManifest,
} from "../definitions/schema.js";
import {
	abiStorePath,
	addressIndexPath,
	artifactPath,
	DEFINITIONS_REL_ROOT,
	DEFINITIONS_ROOT,
	generatedAbiTypesPath,
	generatedChainPath,
	manifestPath,
} from "./lib/definitions/paths.js";
import {
	readAddressIndex,
	readLatestManifest,
	readManifest,
} from "./lib/definitions/persist-deployment.js";

const CORE_CONTRACTS = [
	"FSEnvelopeRegistry",
	"FSPaymentValidator",
	"FSAttachmentRelease",
] as const;

const CONTRACT_ABI_EXPORTS: Record<
	ContractName,
	{ constName: string; typeName: string; artifact: string }
> = {
	FSEnvelopeRegistry: {
		constName: "envelopeRegistryAbi",
		typeName: "FSEnvelopeRegistryAbi",
		artifact: "FSEnvelopeRegistry",
	},
	FSPaymentValidator: {
		constName: "paymentValidatorAbi",
		typeName: "FSPaymentValidatorAbi",
		artifact: "FSPaymentValidator",
	},
	FSAttachmentRelease: {
		constName: "attachmentReleaseAbi",
		typeName: "FSAttachmentReleaseAbi",
		artifact: "FSAttachmentRelease",
	},
	MockUSDC: {
		constName: "mockUsdcAbi",
		typeName: "MockUsdcAbi",
		artifact: "MockUSDCToken",
	},
};

function relImport(target: string) {
	const generatedDir = path.join(DEFINITIONS_ROOT, "generated");
	if (target.startsWith(`${DEFINITIONS_ROOT}${path.sep}`)) {
		const rel = path.relative(generatedDir, target).replace(/\\/g, "/");
		return rel.startsWith(".") ? rel : `./${rel}`;
	}
	return target.replace(new RegExp(`^${DEFINITIONS_REL_ROOT}/`), "../");
}

function abiImportVar(abiRef: string) {
	return `abi_${abiRef.slice(0, 12)}`;
}

function formatWithBiome(path: string) {
	const result = Bun.spawnSync(["bunx", "biome", "check", "--write", path]);
	if (result.exitCode !== 0) {
		throw new Error(
			`biome format failed for ${path}: ${result.stderr.toString()}`,
		);
	}
}

async function readArtifactAbi(artifactName: string): Promise<unknown | null> {
	const path = artifactPath(artifactName);
	const file = Bun.file(path);
	if (!(await file.exists())) return null;
	const artifact = (await file.json()) as { abi?: unknown };
	if (!artifact.abi) return null;
	return artifact.abi;
}

async function generateAbiTypesFromArtifacts() {
	const constBlocks: string[] = [];
	const exportLines: string[] = [];

	for (const name of [...CORE_CONTRACTS, "MockUSDC"] as const) {
		const { artifact, constName, typeName } = CONTRACT_ABI_EXPORTS[name];
		const abi = await readArtifactAbi(artifact);
		if (!abi) continue;
		const varName = `${constName}Value`;
		constBlocks.push(
			`const ${varName} = ${JSON.stringify(abi, null, 2)} as const;`,
		);
		exportLines.push(`export type ${typeName} = typeof ${varName};`);
		exportLines.push(`export const ${constName}: ${typeName} = ${varName};`);
	}

	if (constBlocks.length === 0) {
		const body = `/** AUTO-GENERATED by scripts/gen-definitions.ts — do not edit */
/** Run \`bun compile\` then \`bun gen:definitions\` to populate viem ABI types. */
import type { Abi } from "viem";

export type FSEnvelopeRegistryAbi = Abi;
export type FSPaymentValidatorAbi = Abi;
export type FSAttachmentReleaseAbi = Abi;
export type MockUsdcAbi = Abi;
`;
		await Bun.write(generatedAbiTypesPath(), body);
		console.warn("Skipped abi-types: compile artifacts missing");
		return;
	}

	const body = `/** AUTO-GENERATED by scripts/gen-definitions.ts — do not edit */

${constBlocks.join("\n\n")}

${exportLines.join("\n")}
`;
	await Bun.write(generatedAbiTypesPath(), body);
	console.log(`Generated ${generatedAbiTypesPath()}`);
}

async function ensureChainScaffold(chainKey: ChainKey) {
	const indexPath = addressIndexPath(chainKey);
	const file = Bun.file(indexPath);
	if (!(await file.exists())) {
		await Bun.write(indexPath, "{}\n");
	}
}

async function collectHistoricalEntries(chainKey: ChainKey) {
	const index = await readAddressIndex(chainKey);
	const latest = await readLatestManifest(chainKey);
	const latestAddresses = new Set<string>();
	if (latest) {
		for (const name of CORE_CONTRACTS) {
			latestAddresses.add(latest.contracts[name].address.toLowerCase());
		}
		if (latest.contracts.MockUSDC) {
			latestAddresses.add(latest.contracts.MockUSDC.address.toLowerCase());
		}
	}

	const entries: Array<{
		address: string;
		contractName: string;
		abiRef: string;
	}> = [];

	for (const [address, entry] of Object.entries(index)) {
		if (latestAddresses.has(address.toLowerCase())) continue;
		const manifest = await readManifest(chainKey, entry.deploymentId);
		const ref =
			entry.contractName === "MockUSDC"
				? manifest.contracts.MockUSDC
				: manifest.contracts[entry.contractName];
		if (!ref) continue;
		entries.push({
			address: address.toLowerCase(),
			contractName: entry.contractName,
			abiRef: ref.abiRef,
		});
	}
	return entries;
}

function buildLatestBlock(
	manifest: DeploymentManifest,
	abiVars: Map<string, string>,
) {
	const lines: string[] = ["  latest: {"];
	for (const name of [...CORE_CONTRACTS, "MockUSDC"] as const) {
		const ref = manifest.contracts[name];
		if (!ref) continue;
		const varName = abiVars.get(ref.abiRef);
		if (!varName) throw new Error(`Missing ABI import for ${ref.abiRef}`);
		lines.push(`    ${name}: {`);
		lines.push(`      address: ${JSON.stringify(ref.address)},`);
		lines.push(`      abi: ${varName},`);
		lines.push(`    },`);
	}
	lines.push("  },");
	return lines.join("\n");
}

async function generateChain(chainKey: ChainKey) {
	await ensureChainScaffold(chainKey);

	const manifest = await readLatestManifest(chainKey);
	const historical = await collectHistoricalEntries(chainKey);
	const outPath = generatedChainPath(chainKey);

	if (!manifest) {
		const body = `/** AUTO-GENERATED by scripts/gen-definitions.ts — do not edit */
import type { ChainDefinitionsBundle } from "../bundle-types.js";

export const definitions = {
  latest: null,
  historicalByAddress: {},
  deploymentId: null,
} satisfies ChainDefinitionsBundle;
`;
		await Bun.write(outPath, body);
		return;
	}

	const abiRefs = new Set<string>();
	for (const name of [...CORE_CONTRACTS, "MockUSDC"] as const) {
		const ref = manifest.contracts[name];
		if (ref) abiRefs.add(ref.abiRef);
	}
	for (const entry of historical) {
		abiRefs.add(entry.abiRef);
	}

	const abiVars = new Map<string, string>();
	const abiImports: string[] = [];
	for (const abiRef of [...abiRefs].sort()) {
		const varName = abiImportVar(abiRef);
		abiVars.set(abiRef, varName);
		abiImports.push(
			`import ${varName} from "${relImport(abiStorePath(abiRef))}";`,
		);
	}

	const historicalLines: string[] = [];
	for (const entry of historical.sort((a, b) =>
		a.address.localeCompare(b.address),
	)) {
		const varName = abiVars.get(entry.abiRef);
		if (!varName) continue;
		historicalLines.push(
			`    ${JSON.stringify(entry.address)}: { name: ${JSON.stringify(entry.contractName)}, abi: ${varName} },`,
		);
	}

	const body = `/** AUTO-GENERATED by scripts/gen-definitions.ts — do not edit */
import type { ChainDefinitionsBundle } from "../bundle-types.js";
import manifest from "${relImport(manifestPath(chainKey, manifest.deploymentId))}";

${abiImports.join("\n")}

export const definitions = {
${buildLatestBlock(manifest, abiVars)}
  deploymentId: manifest.deploymentId,
  historicalByAddress: {
${historicalLines.join("\n")}
  },
} satisfies ChainDefinitionsBundle;
`;

	await Bun.write(outPath, body);
	console.log(`Generated ${outPath}`);
}

async function main() {
	for (const chainKey of CHAIN_KEYS) {
		await generateChain(chainKey);
	}
	await generateAbiTypesFromArtifacts();
	formatWithBiome(DEFINITIONS_ROOT);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
