import path from "node:path";
import "@nomicfoundation/hardhat-viem";
import hre from "hardhat";
import { getAddress, parseEther } from "viem";
import { hardhat } from "viem/chains";
import { evmPackageDir } from "./lib/repo-paths.js";

export const LOCAL_MOCK_USDC_RECIPIENT = getAddress(
	"0x4CC33004581cdDe1a4838C9d897260A244f3b4dA",
);

export const LOCAL_MOCK_USDC_MINT_AMOUNT = 10_000_000n * 10n ** 6n;

export const MOCK_USDC_DEF_PATH = path.join(
	evmPackageDir(),
	"definitions/mock-usdc.ts",
);

export const HARDHAT_LOCAL_SERVER = getAddress(
	"0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
);

type MockUsdBundle = {
	readonly address: `0x${string}`;
	abi: unknown;
};

type WalletDeployed = Awaited<ReturnType<typeof hre.viem.getWalletClient>>;
type PublicClientDeployed = Awaited<
	ReturnType<typeof hre.viem.getPublicClient>
>;

export type LocalMockUsdBundle = MockUsdBundle;

export function viemChainOverride(): { chain: typeof hardhat } | undefined {
	if (hre.network.name === "localhost") {
		return { chain: hardhat };
	}
	return undefined;
}

export async function fundLocalServer(
	deployer: WalletDeployed,
	publicClient: PublicClientDeployed,
	serverAddress: `0x${string}`,
) {
	const min = parseEther("1");
	const balance = await publicClient.getBalance({ address: serverAddress });
	if (balance >= min) return;

	const hash = await deployer.sendTransaction({
		account: deployer.account,
		to: serverAddress,
		value: parseEther("100"),
	});
	await publicClient.waitForTransactionReceipt({ hash });
	console.log("Funded server relayer:", serverAddress);
}

export async function fundLocalMockUsdcRecipientForGas(
	deployer: WalletDeployed,
	publicClient: PublicClientDeployed,
	recipientAddress: `0x${string}`,
) {
	// Settlement rules require payer gas (native ETH), even if USDC is the token being transferred.
	const min = parseEther("1");
	const balance = await publicClient.getBalance({ address: recipientAddress });
	if (balance >= min) return;

	const hash = await deployer.sendTransaction({
		account: deployer.account,
		to: recipientAddress,
		value: parseEther("10"),
	});
	await publicClient.waitForTransactionReceipt({ hash });
	console.log("Funded local MockUSDC recipient for gas:", recipientAddress);
}

export async function deployAndFundLocalMockUsd(
	deployer: WalletDeployed,
	publicClient: PublicClientDeployed,
): Promise<MockUsdBundle> {
	const mockUsdc = await hre.viem.deployContract(
		"MockUSDCToken",
		[deployer.account.address],
		{ client: { wallet: deployer } },
	);

	const bundle: MockUsdBundle = {
		address: getAddress(mockUsdc.address),
		abi: mockUsdc.abi,
	};

	const mint = mockUsdc.write.mint;
	if (!mint) {
		throw new Error("MockUSDCToken.mint unavailable");
	}
	const mintHash = await mint([
		LOCAL_MOCK_USDC_RECIPIENT,
		LOCAL_MOCK_USDC_MINT_AMOUNT,
	]);
	await publicClient.waitForTransactionReceipt({ hash: mintHash });
	return bundle;
}

export async function writeMockUsdAddressFile(address: `0x${string}`) {
	const body =
		"/** Auto-generated by scripts/deploy.ts (local Hardhat) — do not edit */\n" +
		`export const LOCAL_MOCK_USDC_ADDRESS = ${JSON.stringify(address)} as const;\n`;
	await Bun.write(MOCK_USDC_DEF_PATH, body);
}
