import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pdfPath = join(root, "activation/assets/welcome-practice.pdf");
const outPath = join(root, "activation/welcome-practice.bytes.ts");

const bytes = await Bun.file(pdfPath).arrayBuffer();
const pdf = new Uint8Array(bytes);
const base64 = Buffer.from(pdf).toString("base64");
const sha256 = `0x${createHash("sha256").update(pdf).digest("hex")}`;

const source = `/** Auto-generated by packages/shared/scripts/embed-welcome-practice-pdf.ts - do not edit. */
const WELCOME_PRACTICE_PDF_BASE64 =
\t"${base64}";

export const WELCOME_PRACTICE_PDF_BYTES: Uint8Array = Uint8Array.from(
\tatob(WELCOME_PRACTICE_PDF_BASE64),
\t(c) => c.charCodeAt(0),
);

export const WELCOME_PRACTICE_PDF_BYTE_LENGTH = ${pdf.byteLength};
export const WELCOME_PRACTICE_PDF_SHA256 = "${sha256}" as const;
`;

await Bun.write(outPath, source);

console.info("Embedded welcome practice PDF");
console.info(`  source: ${pdfPath}`);
console.info(`  output: ${outPath}`);
console.info(`  bytes:  ${pdf.byteLength}`);
console.info(`  sha256: ${sha256}`);
